### ISSUE TITLE
The package id's '' are not valid

### ISSUE THREAD

**Issue by da2x** [martinpitt/cockpit-os-updates#1]
1. Click check for updates (and actually find some updates)
2. Click Install all updates button

Land on error page saying:

    The package id's '' are not valid

If I reload the page between step 1 and 2, things works as expected.

Version 058f0f0.

**Comment by martinpitt** [comment]
I can reproduce something like this if I have *no* available security updates, and use the "Install security updates" button. I know that's not what you said in the description, but could it be that this is what happened? I'll get that fixed.

If you really used the "all" button, can you please run `git pull; npm run compile`? I added some debugging messages. Open the updates page, then open the JavaScript console (Ctrl+Shift+J in Firefox) and install updates. This should produce some logging, please copy&paste it here.

Note that you can go back to some earlier versions with e. g. `sudo dnf downgrade tzdata` (do that for packages where you remember that you had them when you ran into this).

Thanks!

**Comment by martinpitt** [comment]
With latest commit the "Install security" button is not displayed any more if there are no security updates, which prevents that. If that wasn't the reason, I need the above debugging logs, please reopen then. Thanks!

**Comment by da2x** [comment]
I thought I clicked “all updates button”, but perhaps not. I’ll let you know if it happens again!
